name: digital_score_card
description: A new Flutter project.

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.1.0
  intl: ^0.18.1
  pdf: ^3.10.4
  printing: ^5.12.0
